---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(flexmix)
```


## Allele frequencies

```{r}
prob_A <- runif(1)
prob_T <- 1 - prob_A
print(prob_A)
print(prob_T)
```

```{r}
NUM_OBS <- 1000
probs <- c(prob_A ^ 2, 2 * prob_A * prob_T, prob_T ^ 2)
SE <- 0.002

mixture <- data.frame(cluster = sample(1:3, NUM_OBS, replace = TRUE, prob = probs)) %>%
  mutate(x = case_when(
    cluster == 1 ~ rbinom(NUM_OBS, 100, 1 - SE),
    cluster == 2 ~ rbinom(NUM_OBS, 100, 0.5),
    cluster == 3 ~ rbinom(NUM_OBS, 100, SE)
  ))

mixture %>%
  mutate(x = x * 0.01) %>%
  ggplot(aes(x = x)) + 
    geom_bar(aes(y = ..prop.., group = 1), fill = "#009E73") +
    theme_minimal() + 
    xlab("fraction A")
```

```{r}
mixture <- mixture %>%
  mutate(ratio = ifelse(x > 50, (100 - x) / x, x / (100 - x)))

ggplot(mixture, aes(x = ratio)) + 
  geom_bar(aes(y = ..prop.., group = 1), fill = "#009E73") +
  xlab("ratio minor/major allele") +
  theme_minimal() +
  geom_vline(aes(xintercept = 2 * prob_A * prob_T, color = "red"))
```

```{r}
mixture %>% 
  filter(ratio > 2 * prob_A * prob_T) %>%
  ggplot(aes(x = ratio)) +
  geom_bar(aes(y = ..prop..), fill = "#009E73") +
  geom_vline(aes(xintercept = median(ratio), color = "red")) +
  theme_minimal()
```

$$R_i=\frac{min(n_{A_i}, n_{T_i})}{max(n_{A_i}, n_{T_i})}$$
$${n_{A_i}},{n_{T_i}}$$
$$n_{T_i}$$























